### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by boogie666** [garora/TDD-Katas#14]
This isn't really an issue :P

can i use your kata specs (not the code just the readme file) in yeoman tdd-kata generator?
This one right here -> https://github.com/boogie666/generator-tdd-kata

**Comment by garora** [comment]
Hi,
Here we have collected various katas which is opensource. I have no
objection if u wann to use to help others.
I did not get a chance to look into that repository.  I would like to be a
part of that if its a repository for help others.

**Comment by boogie666** [comment]
Wow that was a fast reply.
thx, I'll integrate some of the kata specs in the generator soon.

if you want to help i have no objections :P, submit pull requests and i'll merge in.

basically its a yeoman generator that lets you select which kata you want to do and creates a simple template project with the specs of the kata and a couple of other basic starting files (a test file and a 'main' file etc.).

It just generates some boilerplate in the end, so it's nothing all that special but useful to get a quick start on the kata you want.

yeoman is for scaffolding javascript projects. so for now its just for javascript. that being said i do want to add the option of generating the templates for other languages as well at some point later

cheers

**Comment by boogie666** [comment]
oh btw i put it up on npm 
https://www.npmjs.com/package/generator-tdd-kata

**Comment by garora** [comment]
Good I will take a look in next week.

I have tdd generator repository on bitbucket a private repository. For
various languages.

Thanks

**Comment by garora** [comment]
@boogie666 - I got a chance to visit your tdd-generator repo as well as npm page. It looks awesome!. Is it possible for you to add my repo tdd-kata url/link with your repository/npm page?

My motto is only to serve best TDD Kata practices, I am continuously adding new katas, it will be nice for visitor to get new updates!

Please let me share your views, I will be happy to work.

**Comment by boogie666** [comment]
@garora fork the repo, add your links (and whatever else you want :P ) where you want and submit a pull request. cheers

**Comment by garora** [comment]
@boogie666 - Glad to read that.
I created a simple Pull Request (just added a link in README file). Did not find a way to add the same in npm page.

**Comment by boogie666** [comment]
i need to do a release to npm for that to happen. i'll do what later today

**Comment by garora** [comment]
Thanks for support

On Wed, Apr 1, 2015 at 12:12 PM, boogie666 <notifications@github.com> wrote:

> i need to do a release to npm for that to happen. i'll do what later today
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/garora/TDD-Katas/issues/14#issuecomment-88370353>.
>



-- 
Thanks & Regards,
Gaurav Arora
