### ISSUE TITLE
Can't open TDD-Katas-NETCore

### ISSUE THREAD

**Issue by cjhnim** [garora/TDD-Katas#37]
I've cloned latest repository and I opened the solution (TDD-Katas-project.sln)
As a result, I saw the following errors.

> C:\git\github\TDD-Katas-master\Src\CSharp\Net Core\TDD-Katas-NETCore.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\git\github\TDD-Katas-master\Src\CSharp\Net Core\TDD-Katas-NETCore.csproj

![image](https://user-images.githubusercontent.com/12405424/37383328-76bc855a-278b-11e8-95a7-6c978540573f.png)

Also I attached my VS2015 info.

> Microsoft Visual Studio Professional 2015
> Version 14.0.25424.00 Update 3
> Microsoft .NET Framework
> Version 4.7.02556
> 
> Installed Version: Professional
> 
> LightSwitch for Visual Studio 2015   00322-50052-59877-AA145
> Microsoft LightSwitch for Visual Studio 2015
> 
> Visual Basic 2015   00322-50052-59877-AA145
> Microsoft Visual Basic 2015
> 
> Visual C# 2015   00322-50052-59877-AA145
> Microsoft Visual C# 2015
> 
> Visual C++ 2015   00322-50052-59877-AA145
> Microsoft Visual C++ 2015
> 
> Visual F# 2015   00322-50052-59877-AA145
> Microsoft Visual F# 2015
> 
> Windows Phone SDK 8.0 - ENU   00322-50052-59877-AA145
> Windows Phone SDK 8.0 - ENU
> 
> Application Insights Tools for Visual Studio Package   7.18.00214.2
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
> ASP.NET and Web Tools 2015.1 (Beta8)
> 
> ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
> For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563
> 
> ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
> For additional information, visit http://www.asp.net/
> 
> Clang with Microsoft CodeGen   14.0.25515
> Clang with Microsoft CodeGen
> 
> Command Bus, Event Stream and Async Manager   Merq
> Provides ICommandBus, IEventStream and IAsyncManager MEF services for loosely coupled Visual Studio extension components communication and integration.
> 
> Common Azure Tools   1.8
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> Debugging Tools for Windows   10.0.15063.0
> Integrates the Windows Debugger functionality (http://go.microsoft.com/fwlink/?linkid=223405) in Visual Studio.
> 
> InstallShield Limited Edition   
> InstallShield. For more information visit the Flexera Software website at <http://www.FlexeraSoftware.com>. Copyright © 2015 Flexera Software LLC. All Rights Reserved.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> KofePackagePackage Extension   1.0
> KofePackagePackage Visual Studio Extension Detailed Info
> 
> Microsoft Azure Mobile Services Tools   1.4
> Microsoft Azure Mobile Services Tools
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> NuGet Package Manager   3.4.4
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
> Microsoft Office Developer Tools for Visual Studio 2015 ENU
> 
> PreEmptive Analytics Visualizer   1.2
> Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
> 
> Python Tools for Visual Studio   2.2.50113.00
> Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.
> 
> Python Tools for Visual Studio - Django Integration   2.2.50113.00
> Provides templates and integration for the Django web framework.
> 
> Python Tools for Visual Studio - Profiling Support   2.2.50113.00
> Profiling support for Python projects.
> 
> Sandcastle Help File Builder   SHFB
> Visual Studio integration for the Sandcastle Help File Builder.
> https://GitHub.com/EWSoftware/SHFB
> 
> SQL Server Data Tools   14.0.60519.0
> Microsoft SQL Server Data Tools
> 
> TypeScript   1.8.35.0
> TypeScript tools for Visual Studio
> 
> Visual C++ for Cross Platform Mobile Development (Android)   14.0.25401.00
> Visual C++ for Cross Platform Mobile Development (Android)
> 
> Visual C++ for Cross Platform Mobile Development (iOS)   14.0.25401.00
> Visual C++ for Cross Platform Mobile Development (iOS)
> 
> Visual Studio Tools for Apache Cordova   Update 10
> Visual Studio Tools for Apache Cordova
> 
> Visual Studio Tools for Unity   2.8.0.0
> Visual Studio Tools for Unity
> 
> Visual Studio Tools for Universal Windows Apps   14.0.25527.01
> The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
> 
> Windows Driver Kit   10.0.15063.0
> Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)
> 
> Workflow Manager Tools 1.0   1.0
> This package contains the necessary Visual Studio integration components for Workflow Manager.
> 
> Xamarin   4.2.1.62 (680125b)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin.Android   7.0.2.37 (ce955cc)
> Visual Studio extension to enable development for Xamarin.Android.
> 
> Xamarin.iOS   10.2.1.5 (44931ae)
> Visual Studio extension to enable development for Xamarin.iOS.

   **Task to trace and resolve this issue:**
- [x] Check the problem
- [x] Check the problem in previous versions
- [x] Provide solutions

**Comment by garora** [comment]
@cjhnim - Can you please try the branch other than master and dev ?

**Comment by cjhnim** [comment]
I've tried checkout and build at both master and develop branch.
As a result, they are same error.
![image](https://user-images.githubusercontent.com/12405424/37887643-ea29c464-30fd-11e8-8e9f-c4f8eb2eb4ec.png)

**Comment by garora** [comment]
Thanks for your help to understand the issue. Give me couple of hours, I ll see and fix it, if any issue exist.




Get Outlook for Android







On Mon, Mar 26, 2018 at 10:29 AM +0530, "Choi Jung Hyun" <notifications@github.com> wrote:












I've tried checkout and build at both master and develop branch.

As a result, they are same error.

**Comment by garora** [comment]
- [ ] Check the problem
- [ ] Check the problem in previous versions
- [ ] Provide solutions

**Comment by garora** [comment]
I tried this using `Visual Studio 2017 update 3` and all tests are passed. 

![nunit-tests](https://user-images.githubusercontent.com/966457/37938820-50f953b0-317d-11e8-814a-04015eaeecba.png)

You are using `Visual Studio 2015` - I suggest you to please downgrade .NET Core version to 1.1 - refer to: [Can .net core 2.0 project be opened by VS 2015?](https://github.com/dotnet/core/issues/685).

There is a separate repository for .NET Core. You can Fork it from here: [TDD-Katas-NETCore](https://github.com/garora/TDD-Katas-NETCore)
