### ISSUE TITLE
Create wiki page

### ISSUE THREAD

**Issue by garora** [garora/TDD-Katas#6]
There is a long list of katas in readme.md file and many more are in line. To make short this file, I propose to create a wiki page describing all the details about katas. 

Afterwards, readme.md file would be simply contain definitions of specific kata. Lets give your hand to start this.

Thanks,
Gaurav Arora

**Comment by garora** [comment]
Created Git Page using default template and text at: http://garora.github.io/TDD-Katas. I will modify text and related items later-on.

**Comment by shubyarora** [comment]
@garora - are you still working on it. Please see my other issue, I just logged

**Comment by garora** [comment]
Shuby,
Yes,I am still working on this.
Regarding the other issue you mentioned- Justin already replied. Actually
that is not an issue.

**Comment by garora** [comment]
All,

This is all yours, your helping hands will be most valuable to make this repository more powerful and vast so, everyone can understand the value of TDD Katas.

Provide your feedback for : Explained 'Learning Test Driven Development with TDD Katas' : http://goo.gl/5NYpVI

@shubyarora @marisks  @justinkurtz  @matjos  @SeanKilleen  @Hassankashi

**Comment by garora** [comment]
Closing!
